// Generated by vinoa. Module: platform-independent logic.
// The core module must never import a server API: it has to stay loadable on every target.
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
}

description = "Platform-independent logic for {{ pluginName }}."

// The compiler targets the LOWEST Java level among the enabled modules.
val targetJava = {{ coreJavaTarget }}

if (targetJava >= 17) {
    // Modern target: use a matching JDK toolchain. Gradle discovers an installed JDK (or
    // provisions one when the foojay resolver is enabled); --release would instead require the
    // JVM running Gradle to be at least as new as the target.
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(targetJava)
        }
    }
} else {
    // Legacy target: --release keeps working on whatever JVM runs Gradle.
    tasks.withType<JavaCompile>().configureEach {
        options.release = targetJava
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}
{% if cap_quality %}
val junitBom = if ({{ coreJavaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ coreJavaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

dependencies {
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
}
{% endif %}
