// Generated by vinoa. Module: platform-independent logic.
// The core module must never import a server API: it has to stay loadable on every target.
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
}

description = "Platform-independent logic for {{ pluginName }}."

// The compiler targets the LOWEST Java level among the enabled modules.
// Gradle itself keeps running on its own JVM; --release pins the bytecode level.
tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release = {{ coreJavaTarget }}
}
{% if cap_toolchain_download %}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of({{ coreJavaTarget }})
    }
}
{% endif %}
{% if cap_quality %}
val junitBom = if ({{ coreJavaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ coreJavaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}

dependencies {
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
}
{% endif %}
