// Generated by vinoa. Module: Velocity proxy adapter (experimental skeleton).
// Velocity has no resources/ directory: the descriptor is generated into the jar root by the
// @Plugin annotation processor.
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
}

description = "Velocity proxy adapter for {{ pluginName }} (experimental)."

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release = {{ javaTarget }}
}
{% if cap_toolchain_download %}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of({{ javaTarget }})
    }
}
{% endif %}
{% if cap_quality %}
val junitBom = if ({{ javaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ javaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
{% endif %}
dependencies {
    implementation(project(":core"))
    compileOnly(libs.velocity.api)
    annotationProcessor(libs.velocity.api)
{% if cap_quality %}
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
{% endif %}
}
