// Generated by vinoa. Module: Paper adapter.
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
{% if cap_run_paper %}
    alias(libs.plugins.run.paper)
{% endif %}
}

description = "Paper adapter for {{ pluginName }}."

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release = {{ javaTarget }}
}
{% if cap_toolchain_download %}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of({{ javaTarget }})
    }
}
{% endif %}
{% if cap_quality %}
val junitBom = if ({{ javaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ javaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
{% endif %}
dependencies {
    implementation(project(":core"))
    compileOnly(libs.paper.api)
{% if cap_quality %}
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
{% endif %}
}

// The only build-time substitution: the plugin version. Everything else is baked in at
// generate time, so the build never needs the version matrix or the network.
tasks.processResources {
    val props = mapOf("version" to project.version)
    inputs.properties(props)
{% if is_paper_metadata %}
    filesMatching("paper-plugin.yml") { expand(props) }
{% else %}
    filesMatching("plugin.yml") { expand(props) }
{% endif %}
}
{% if cap_run_paper %}
tasks {
    runServer {
        minecraftVersion("{{ mcVersion }}")
    }
}
{% endif %}
