// Generated by vinoa. Module: Folia adapter (experimental).
// Folia shares the Bukkit API surface but replaces the scheduler; see Main.java for the
// regionised scheduling note. There is no run-paper task for Folia.
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
}

description = "Folia adapter for {{ pluginName }} (experimental)."

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release = {{ javaTarget }}
}
{% if cap_toolchain_download %}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of({{ javaTarget }})
    }
}
{% endif %}
{% if cap_quality %}
val junitBom = if ({{ javaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ javaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
{% endif %}
dependencies {
    implementation(project(":core"))
    compileOnly(libs.folia.api)
{% if cap_quality %}
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
{% endif %}
}

tasks.processResources {
    val props = mapOf("version" to project.version)
    inputs.properties(props)
{% if is_paper_metadata %}
    filesMatching("paper-plugin.yml") { expand(props) }
{% else %}
    filesMatching("plugin.yml") { expand(props) }
{% endif %}
}
