// Generated by vinoa. Module: Folia adapter (experimental).
// Folia shares the Bukkit API surface but replaces the scheduler; see Main.java for the
// regionised scheduling note. There is no run-paper task for Folia.
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
{% if cap_coverage %}
    jacoco
{% endif %}
{% if cap_spotbugs %}
    alias(libs.plugins.spotbugs)
{% endif %}
}

description = "Folia adapter for {{ pluginName }} (experimental)."

val targetJava = {{ javaTarget }}

if (targetJava >= 17) {
    // Modern target: compile with a matching JDK toolchain. Gradle discovers an installed JDK
    // (or provisions one when the foojay resolver is enabled), so the JVM running Gradle does
    // not have to match the target. --release would require that it did.
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(targetJava)
        }
    }
} else {
    // Legacy target: --release on whatever JVM runs Gradle, so a Java 8 target needs no JDK 8.
    tasks.withType<JavaCompile>().configureEach {
        options.release = targetJava
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}
{% if cap_quality %}
val junitBom = if ({{ javaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ javaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
{% endif %}
dependencies {
    implementation(project(":core"))
    compileOnly(libs.folia.api)
{% if cap_quality %}
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
{% endif %}
}

tasks.processResources {
    val props = mapOf("version" to project.version)
    inputs.properties(props)
{% if is_paper_metadata %}
    filesMatching("paper-plugin.yml") { expand(props) }
{% else %}
    filesMatching("plugin.yml") { expand(props) }
{% endif %}
}

{% if cap_spotbugs %}
spotbugs {
    // A modern target uses the current SpotBugs line; a Java 8 target needs the 4.8.x line.
    toolVersion = if (targetJava <= 8) libs.versions.spotbugsLegacy.get() else libs.versions.spotbugsModern.get()
    effort = "max"
    reportLevel = "medium"
}
tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach {
    reports.create("html") { required.set(true) }
}
{% endif %}
{% if cap_coverage %}
tasks.withType<org.gradle.testing.jacoco.tasks.JacocoReport>().configureEach {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}
{% endif %}

// Integration tests live in their own source set and their own task: `check` must NOT depend
// on them, so a plain `./gradlew build` stays fast and offline-friendly.
val mainOutput = sourceSets.main.get().output
val integrationTest = sourceSets.create("integrationTest") {
    compileClasspath += mainOutput
    runtimeClasspath += mainOutput
}
configurations["integrationTestImplementation"].extendsFrom(configurations.testImplementation.get())
configurations["integrationTestRuntimeOnly"].extendsFrom(configurations.testRuntimeOnly.get())

tasks.register<Test>("integrationTest") {
    description = "Runs the integration tests (not part of `check`)."
    group = "verification"
    testClassesDirs = integrationTest.output.classesDirs
    classpath = integrationTest.runtimeClasspath
    shouldRunAfter(tasks.test)
}
