import org.gradle.api.plugins.quality.Checkstyle

// Generated by vinoa. Root script: shared conventions only.
// No platform dependency is declared here; each platform module owns its own coordinates.
// All versions come from gradle/libs.versions.toml.
allprojects {
    group = "{{ packageName }}"
    version = "{{ projectVersion }}"
}

subprojects {
    repositories {
        mavenCentral()
        maven("https://repo.papermc.io/repository/maven-public/") {
            name = "papermc"
        }
    }
{% if cap_quality %}
    // Checkstyle is applied by the modules; the shared rules and the resolution of
    // config/checkstyle/suppressions.xml are wired once, here.
    plugins.withId("checkstyle") {
        tasks.withType<Checkstyle>().configureEach {
            configFile = rootProject.file("config/checkstyle/checkstyle.xml")
            maxWarnings = 0
            reports {
                xml.required.set(true)
                html.required.set(true)
            }
        }
    }
{% endif %}
}
