// Generated by vinoa. Build comments stay in English on purpose (encoding/tooling stability).
// One build, one version catalog, one Gradle module per selected platform.
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven("https://repo.papermc.io/repository/maven-public/") {
            name = "papermc"
        }
    }
}
{% if cap_toolchain_download %}
// Opt-in: let Gradle download the JDK a module asks for when the machine lacks it.
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
{% endif %}
rootProject.name = "{{ projectName }}"

// "core" first, then every selected platform in the fixed priority order.
include("core"{% for p in platforms %}, "platforms:{{ p }}"{% endfor %})
