// Generated by vinoa. Module: Sponge adapter (experimental).
// SpongeAPI changes its lifecycle API between release lines, so this module is a skeleton:
// the registration calls must be written against the API line the version matrix selected.
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
}

description = "Sponge adapter for {{ pluginName }} (experimental)."

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release = {{ javaTarget }}
}
{% if cap_toolchain_download %}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of({{ javaTarget }})
    }
}
{% endif %}
{% if cap_quality %}
val junitBom = if ({{ javaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ javaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
{% endif %}
// SpongeAPI is published as -SNAPSHOT for most release lines, so this module needs
// Sponge's own repository in addition to the shared ones declared in the root build script.
repositories {
    maven("https://repo.spongepowered.org/repository/maven-public/") {
        name = "spongepowered"
    }
}

dependencies {
    implementation(project(":core"))
    compileOnly(libs.sponge.api)
{% if cap_quality %}
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
{% endif %}
}
