// Generated by vinoa. Module: BungeeCord proxy adapter (experimental skeleton).
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
}

description = "BungeeCord proxy adapter for {{ pluginName }} (experimental)."

val targetJava = {{ javaTarget }}

if (targetJava >= 17) {
    // Modern target: compile with a matching JDK toolchain. Gradle discovers an installed JDK
    // (or provisions one when the foojay resolver is enabled), so the JVM running Gradle does
    // not have to match the target. --release would require that it did.
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(targetJava)
        }
    }
} else {
    // Legacy target: --release on whatever JVM runs Gradle, so a Java 8 target needs no JDK 8.
    tasks.withType<JavaCompile>().configureEach {
        options.release = targetJava
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}
{% if cap_quality %}
val junitBom = if ({{ javaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ javaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
{% endif %}
dependencies {
    implementation(project(":core"))
    compileOnly(libs.bungeecord.api)
{% if cap_quality %}
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
{% endif %}
}

tasks.processResources {
    val props = mapOf("version" to project.version)
    inputs.properties(props)
    filesMatching("plugin.yml") { expand(props) }
}
