// Generated by vinoa. Module: BungeeCord proxy adapter (experimental skeleton).
plugins {
    `java-library`
{% if cap_quality %}
    checkstyle
{% endif %}
}

description = "BungeeCord proxy adapter for {{ pluginName }} (experimental)."

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release = {{ javaTarget }}
}
{% if cap_toolchain_download %}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of({{ javaTarget }})
    }
}
{% endif %}
{% if cap_quality %}
val junitBom = if ({{ javaTarget }} <= 8) libs.junit.bom.legacy else libs.junit.bom.modern

checkstyle {
    toolVersion = if ({{ javaTarget }} <= 8) libs.versions.checkstyleLegacy.get() else libs.versions.checkstyleModern.get()
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
{% endif %}
dependencies {
    implementation(project(":core"))
    compileOnly(libs.bungeecord.api)
{% if cap_quality %}
    testImplementation(platform(junitBom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
{% endif %}
}

tasks.processResources {
    val props = mapOf("version" to project.version)
    inputs.properties(props)
    filesMatching("plugin.yml") { expand(props) }
}
